In [1]:
import pandas as pd

rst_df = pd.read_csv('data/Louisville_Metro_KY_-_Restaurant_Inspection_Scores.csv')

In [2]:
#inspect
print(rst_df.shape)
rst_df.head(10)

(11230, 17)

,EstablishmentID,InspectionID,Ins_TypeDesc,EstablishmentName,PlaceName,Address,Address2,City,State,Zip,TypeDescription,InspectionDate,score,Grade,NameSearch,Intersection,ObjectId
0,29956,1684470,REGULAR,CVS #6211,NaN,3721 LEXINGTON RD,NaN,LOUISVILLE,KY,40207,PRE-PACKAGED RETAIL,2022/07/06 00:00:00,100,NaN,CVS #6211,NaN,1
1,29967,1699737,REGULAR,NEIGHBORHOOD FOOD MART,NaN,542 LAMPTON ST,NaN,LOUISVILLE,KY,40203,SUPERMARKET WITH PROCESSING,2022/09/07 00:00:00,97,NaN,NEIGHBORHOOD FOOD MART,NaN,2
2,29979,1698679,REGULAR,CIRCLE K #4700075,NaN,1630 ARTHUR ST,NaN,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,97,A,CIRCLE K #4700075,NaN,3
3,29979,1698680,REGULAR,CIRCLE K #4700075,NaN,1630 ARTHUR ST,NaN,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,98,NaN,CIRCLE K #4700075,NaN,4
4,29979,1731827,REGULAR,CIRCLE K #4700075,NaN,1630 ARTHUR ST,NaN,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/01/27 00:00:00,95,A,CIRCLE K #4700075,NaN,5
5,29979,1731828,REGULAR,CIRCLE K #4700075,NaN,1630 ARTHUR ST,NaN,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/01/27 00:00:00,97,NaN,CIRCLE K #4700075,NaN,6
6,30043,1700824,FOLLOWUP,F&Y SUPERMARKET,NaN,3801 W MARKET ST,NaN,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/12 00:00:00,98,NaN,F&Y SUPERMARKET,NaN,7
7,30043,1698630,REGULAR,F&Y SUPERMARKET,NaN,3801 W MARKET ST,NaN,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,94,A,F&Y SUPERMARKET,NaN,8
8,30043,1698631,REGULAR,F&Y SUPERMARKET,NaN,3801 W MARKET ST,NaN,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,95,NaN,F&Y SUPERMARKET,NaN,9
9,30043,1735940,REGULAR,F&Y SUPERMARKET,NaN,3801 W MARKET ST,NaN,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/02/17 00:00:00,94,A,F&Y SUPERMARKET,NaN,10

# Fix two issues with the data set

## 1. Remove columns with only NaN values

In [3]:
#Drop the PlaceName, Address2, and Intersection columns
rst_df = rst_df.dropna(axis=1, how='all')
rst_df.head(10)

,EstablishmentID,InspectionID,Ins_TypeDesc,EstablishmentName,Address,City,State,Zip,TypeDescription,InspectionDate,score,Grade,NameSearch,ObjectId
0,29956,1684470,REGULAR,CVS #6211,3721 LEXINGTON RD,LOUISVILLE,KY,40207,PRE-PACKAGED RETAIL,2022/07/06 00:00:00,100,NaN,CVS #6211,1
1,29967,1699737,REGULAR,NEIGHBORHOOD FOOD MART,542 LAMPTON ST,LOUISVILLE,KY,40203,SUPERMARKET WITH PROCESSING,2022/09/07 00:00:00,97,NaN,NEIGHBORHOOD FOOD MART,2
2,29979,1698679,REGULAR,CIRCLE K #4700075,1630 ARTHUR ST,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,97,A,CIRCLE K #4700075,3
3,29979,1698680,REGULAR,CIRCLE K #4700075,1630 ARTHUR ST,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,98,NaN,CIRCLE K #4700075,4
4,29979,1731827,REGULAR,CIRCLE K #4700075,1630 ARTHUR ST,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/01/27 00:00:00,95,A,CIRCLE K #4700075,5
5,29979,1731828,REGULAR,CIRCLE K #4700075,1630 ARTHUR ST,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/01/27 00:00:00,97,NaN,CIRCLE K #4700075,6
6,30043,1700824,FOLLOWUP,F&Y SUPERMARKET,3801 W MARKET ST,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/12 00:00:00,98,NaN,F&Y SUPERMARKET,7
7,30043,1698630,REGULAR,F&Y SUPERMARKET,3801 W MARKET ST,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,94,A,F&Y SUPERMARKET,8
8,30043,1698631,REGULAR,F&Y SUPERMARKET,3801 W MARKET ST,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,95,NaN,F&Y SUPERMARKET,9
9,30043,1735940,REGULAR,F&Y SUPERMARKET,3801 W MARKET ST,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/02/17 00:00:00,94,A,F&Y SUPERMARKET,10

## 2. Remove rows with null values

In [4]:
#check how many null values
print("Null values before dropping: ", rst_df.isnull().sum().sum())

Null values before dropping:  5317

In [5]:
#remove rows with null values
rst_df = rst_df.dropna()

In [6]:
#check if removing null values worked by checking how many null values 
print("Null values after dropping: ", rst_df.isnull().sum().sum())

Null values after dropping:  0

In [7]:
rst_df.head()

,EstablishmentID,InspectionID,Ins_TypeDesc,EstablishmentName,Address,City,State,Zip,TypeDescription,InspectionDate,score,Grade,NameSearch,ObjectId
2,29979,1698679,REGULAR,CIRCLE K #4700075,1630 ARTHUR ST,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,97,A,CIRCLE K #4700075,3
4,29979,1731827,REGULAR,CIRCLE K #4700075,1630 ARTHUR ST,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/01/27 00:00:00,95,A,CIRCLE K #4700075,5
7,30043,1698630,REGULAR,F&Y SUPERMARKET,3801 W MARKET ST,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,94,A,F&Y SUPERMARKET,8
9,30043,1735940,REGULAR,F&Y SUPERMARKET,3801 W MARKET ST,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/02/17 00:00:00,94,A,F&Y SUPERMARKET,10
11,30085,1705774,REGULAR,SPEEDWAY #9709,4239 POPLAR LEVEL RD,LOUISVILLE,KY,40213,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/10/03 00:00:00,96,A,SPEEDWAY #9709,12

## 3. (just in case) Correct column names

In [8]:
rst_df = rst_df.rename(columns={'Ins_TypeDesc': 'InspectionType', 'TypeDescription': 'Type_Size'})
rst_df.head()

,EstablishmentID,InspectionID,InspectionType,EstablishmentName,Address,City,State,Zip,Type_Size,InspectionDate,score,Grade,NameSearch,ObjectId
2,29979,1698679,REGULAR,CIRCLE K #4700075,1630 ARTHUR ST,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,97,A,CIRCLE K #4700075,3
4,29979,1731827,REGULAR,CIRCLE K #4700075,1630 ARTHUR ST,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/01/27 00:00:00,95,A,CIRCLE K #4700075,5
7,30043,1698630,REGULAR,F&Y SUPERMARKET,3801 W MARKET ST,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,94,A,F&Y SUPERMARKET,8
9,30043,1735940,REGULAR,F&Y SUPERMARKET,3801 W MARKET ST,LOUISVILLE,KY,40212,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/02/17 00:00:00,94,A,F&Y SUPERMARKET,10
11,30085,1705774,REGULAR,SPEEDWAY #9709,4239 POPLAR LEVEL RD,LOUISVILLE,KY,40213,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/10/03 00:00:00,96,A,SPEEDWAY #9709,12