In [1]:
import requests
import pandas as pd
from pandas.io.json import json_normalize
import numpy as np

In [2]:
# Pull in data from an API. 
url = "http://universities.hipolabs.com/search?country=United+States"
r = requests.get(url)

In [3]:
data = r.json()
df = pd.DataFrame(data)
df.head(20)

,country,alpha_two_code,name,state-province,domains,web_pages
0,United States,US,Marywood University,None,[marywood.edu],[http://www.marywood.edu]
1,United States,US,Lindenwood University,None,[lindenwood.edu],[http://www.lindenwood.edu/]
2,United States,US,Sullivan University,None,[sullivan.edu],[https://sullivan.edu/]
3,United States,US,Florida State College at Jacksonville,None,[fscj.edu],[https://www.fscj.edu/]
4,United States,US,Xavier University,None,[xavier.edu],[https://www.xavier.edu/]
5,United States,US,Tusculum College,None,[tusculum.edu],[https://home.tusculum.edu/]
6,United States,US,Claremont School of Theology,None,[cst.edu],[https://cst.edu/]
7,United States,US,Columbia College (SC),None,[columbiasc.edu],[https://www.columbiasc.edu/]
8,United States,US,Chabot-Las Positas Community College District,None,[clpccd.edu],[http://www.clpccd.edu/]
9,United States,US,Keller Graduate School of Management,None,[keller.edu],[https://www.keller.edu/]
10,United States,US,Monroe College,None,[monroecollege.edu],[https://monroecollege.edu/]
11,United States,US,San Mateo County Community College District,None,[smccd.edu],[https://smccd.edu/]
12,United States,US,Los Rios Community College District,None,[losrios.edu],[http://losrios.edu/]
13,United States,US,DigiPen Institute of Technology,None,[digipen.edu],[https://www.digipen.edu/]
14,United States,US,University of Pittsburgh Medical Center,Pennsylvania,"[upmc.edu, upmc.com]",[https://www.upmc.com/]
15,United States,US,Claremont Graduate University,None,[cgu.edu],[https://www.cgu.edu/]
16,United States,US,University of Texas Rio Grande Valley,None,[utrgv.edu],[http://www.utrgv.edu/]
17,United States,US,College of Mount Saint Vincent,None,[mountsaintvincent.edu],[https://mountsaintvincent.edu/]
18,United States,US,University of Arkansas System eVersity,None,[uasys.edu],[https://www.uasys.edu/]
19,United States,US,ECPI University,None,[ecpi.edu],[https://www.ecpi.edu/]

In [4]:
df.tail(20)

,country,alpha_two_code,name,state-province,domains,web_pages
4546,United States,US,Shaw University,None,[shawu.edu],[https://www.shawu.edu/]
4547,United States,US,Simmons College of Kentucky,None,[simmonscollegeky.edu],[https://simmonscollegeky.edu/]
4548,United States,US,South Carolina State University,None,[scsu.edu],[https://scsu.edu/]
4549,United States,US,Southern University at New Orleans,None,[suno.edu],[https://www.suno.edu/]
4550,United States,US,Southwestern Christian College,None,[swcc.edu],[https://www.swcc.edu/]
4551,United States,US,St. Augustine's University,None,[st-aug.edu],[https://www.st-aug.edu/]
4552,United States,US,St. Philip's College,None,[alamo.edu],[https://www.alamo.edu/spc/]
4553,United States,US,Stillman College,None,[stillman.edu],[https://stillman.edu/]
4554,United States,US,Talladega College,None,[talladega.edu],[https://www.talladega.edu/]
4555,United States,US,Texas College,None,[texascollege.edu],[https://www.texascollege.edu/]
4556,United States,US,The Lincoln University,None,[lincoln.edu],[https://www.lincoln.edu/]
4557,United States,US,Tougaloo College,None,[tougaloo.edu],[https://www.tougaloo.edu/]
4558,United States,US,Virginia Union University,None,[vuu.edu],[https://www.vuu.edu/]
4559,United States,US,Virginia University of Lynchburg,None,[vul.edu],[https://www.vul.edu/]
4560,United States,US,Voorhees University,None,[voorhees.edu],[https://www.voorhees.edu/]
4561,United States,US,West Virginia State University,None,[wvstate.edu],[https://www.wvstateu.edu/]
4562,United States,US,Wiley College,None,[wileyc.edu],[https://www.wileyc.edu/]
4563,United States,US,Winston-Salem State University,None,[wssu.edu],[https://www.wssu.edu/]
4564,United States,US,Unity College,None,[unity.edu],[https://unity.edu/]
4565,United States,US,Catawba College,None,[catawba.edu],[https://catawba.edu/]

In [5]:
# Find and print TWO descriptive statistics about your data.(1)
df.describe()

,country,alpha_two_code,name,state-province,domains,web_pages
count,4566,4566,4566,124,4566,4566
unique,1,1,2272,21,2257,2280
top,United States,US,Glendale Community College,Pennsylvania,[ccc.edu],[http://www.cmc.edu/]
freq,4566,4566,4,56,14,4

In [6]:
# Find and print TWO descriptive statistics about your data. (2)
df['state-province'].replace('None', np.nan)
null_count = df['state-province'].isnull().sum()
print("Number of Null Values in the state-province column:", null_count)

Number of Null Values in the state-province column: 4442

In [7]:
# Write a query in Pandas to select a particular set of your data. 
subset = df.query("`state-province`.notnull()")
print(subset)

            country alpha_two_code                                       name  \
14    United States             US    University of Pittsburgh Medical Center
99    United States             US                 College of Southern Nevada
197   United States             US      Bloomsburg University of Pennsylvania
243   United States             US      California University of Pennsylvania
283   United States             US         Clarion University of Pennsylvania
...             ...            ...                                        ...
4494  United States             US                           Bellevue College
4495  United States             US                        CUNY Lehman College
4496  United States             US  CUNY John Jay College of Criminal Justice
4497  United States             US                        CUNY Hunter College
4498  United States             US                          CUNY York College

     state-province                domains                       web_pages
14     Pennsylvania   [upmc.edu, upmc.com]         [https://www.upmc.com/]
99               NV              [csn.edu]          [https://www.csn.edu/]
197    Pennsylvania           [bloomu.edu]        [http://www.bloomu.edu/]
243    Pennsylvania              [cup.edu]           [http://www.cup.edu/]
283    Pennsylvania          [clarion.edu]       [http://www.clarion.edu/]
...             ...                    ...                             ...
4494     Washington  [bellevuecollege.edu]   [https://bellevuecollege.edu]
4495   New York, NY      [lehman.cuny.edu]  [https://www.lehman.cuny.edu/]
4496   New York, NY        [jjay.cuny.edu]    [https://www.jjay.cuny.edu/]
4497   New York, NY      [hunter.cuny.edu]      [https://hunter.cuny.edu/]
4498   New York, NY        [york.cuny.edu]    [https://www.york.cuny.edu/]

[124 rows x 6 columns]

In [11]:
# Select and print the SECOND AND THIRD columns of your data frame.
subset_columns = subset[['alpha_two_code', 'name']]
print(subset_columns)

     alpha_two_code                                       name
14               US    University of Pittsburgh Medical Center
99               US                 College of Southern Nevada
197              US      Bloomsburg University of Pennsylvania
243              US      California University of Pennsylvania
283              US         Clarion University of Pennsylvania
...             ...                                        ...
4494             US                           Bellevue College
4495             US                        CUNY Lehman College
4496             US  CUNY John Jay College of Criminal Justice
4497             US                        CUNY Hunter College
4498             US                          CUNY York College

[124 rows x 2 columns]

In [16]:
# Select and print the FIRST 4 rows of you data frame.
subset_rows = subset.head(4)
print(subset_rows)

           country alpha_two_code                                     name  \
14   United States             US  University of Pittsburgh Medical Center
99   United States             US               College of Southern Nevada
197  United States             US    Bloomsburg University of Pennsylvania
243  United States             US    California University of Pennsylvania

    state-province               domains                 web_pages
14    Pennsylvania  [upmc.edu, upmc.com]   [https://www.upmc.com/]
99              NV             [csn.edu]    [https://www.csn.edu/]
197   Pennsylvania          [bloomu.edu]  [http://www.bloomu.edu/]
243   Pennsylvania             [cup.edu]     [http://www.cup.edu/]